### ISSUE TITLE
Response time significantly much higher in lastest version of LIBNFC?

### ISSUE THREAD

**Issue by amoeles** [nfc-tools/libnfc#354]
Here the time experiment with same commands on mfcuk and mfoc and the same tag&reader but diferent versions of nfc-tools.

**Results (min aprox):**
- **LIBNFC 1.5.1** mfcuk 0.3.3 & mfoc 0.10.3 > Time to obtain all keys: **15 min** (2min mfcuk and 10min mfoc with only one probe by sector)
- **LIBNFC 1.7.1** mfcuk 0.3.8 &  & mfoc 0.10.7 > Time to obtain all keys:  **60 min** (15min mfcuk and 45min mfoc with 20-45 probes by sector)

_In two case i use these commands: "mfcuk -C -R 0:A -v 2" and "mfoc -k xxxxxxxxxxx -O keys.mfd -P 100"
Tag&reader: Mifare classic 1k tag, reader SCL3711._

**Why the lastest version of nfc-tools are more slow?**

**Comment by doegox** [comment]
Total time may result a lot between experiments independently of the libnfc version.

Results of my experiments with an ASK LoGO:

- **Libnfc 1.5.1** mfoc-0.10.2-10-g2be6d8d (there is no tag 0.10.3, this one should be roughly the same version) > Time to obtain 30/32 keys: **39.5 min** and 209 probes so 11.34s/probe

- **Libnfc 1.7.1** mfoc-0.10.7 > Time to obtain 30/32 keys: **29 min** and 156 probes so 11.15s/probe

So you see I got luckier with libnfc 1.7.1 rather than 1.5.1 but the transaction time is about the same
