### ISSUE TITLE
Nfc-list Error. Please help me 

### ISSUE THREAD

**Issue by lyqingye** [nfc-tools/libnfc#406]
NfC open failed. For acr122 usb 002. 007. The reader is acr122u. , Ubuntu. 16.04.  Please help me

**Comment by smortex** [comment]
You need to give us more information on how to reproduce an issue, otherwise there is nothing we can do. 

As it is described here, it look like a usage problem (which would better fit on [Stack Overflow](http://stackoverflow.com/questions/tagged/lib-nfc/), where a wider community will be able to help you), so closing for now .  Please reopen and provide details if you are facing an actual bug. Thanks!
